backend:
  name: git-gateway
  branch: main

local_backend: true
# change url to a link to the image you want to use, no file paths, must be a URL
logo_url: https://ff4ff7783ee60d49edbf6fbf52a263033fe9546a23441529843028b-apidata.googleusercontent.com/download/storage/v1/b/product-petq/o/roma.png?jk=AS1gM8O2isyfbVcPe2I3Gn5rJhl761cRFBMNQYH5VyBbKrC4PIBZJqGguUpDKAx8hixKb0sYfY6yiOU9RvtfKZzyfj3siggQ9xYqe4qpfl32WsanFvitZSPRLRWeWqlrX_j36odKd-PzB0N_OS6b6vBmYDIa3et85XjBiplx_5gN5Yh55w75nrNGpZeWpwCpSXZX1CcXlIP8clNqQPyFFY874vMc0YcOaxir7rNMisZ8o6ndSfK7MPQ-FiCMkYONOXZXTTozDG0m8NTeBdxTV6bL_N5gt16PMns_yLgjedNyRTQpQDvBFraj8Kk51eQsAf7GVDrcZn-90muubC6X4KT47XQfRNho6hv4Q5lPR4v1Jji7oDi9jIV7-IW9Xt0nIn2628e8p5RPhbLhYg0NZxv-aczhxgyKf872qUOzDTNsdFLbaKQ7dynEvozLNIFaJ4SAzN-X-jQ9Ul9A3hsMMDHfkUHZOx3Xn-LE5poTZPJ2OOCnQ-BV3ISkkLd517P4zcGgNiADYqHnl5-sQKQOke0tjApBC8WykpjxKBQ9XRq7-NxPh5qKpPO0pr7qGknJUiXfj70kav8QW3qsRenaQzkSkGR5RvbtIWIXx86lbT4l0cKN3SVZVIVqMsOzf2qMW3nU8DtsZ4sAz0PtfSQGyx6EcX_4b0CPEoaJJrvZ5eqj87o8FjFS3G4HQGl1xnzcVGhRDkSNcI_MHe2uOL9gd85dbT-Lys40B1hw8dhiHfysXWVRs29bzDB4sPgx8BOMUrYXUSwlkZTWxA5it2HASPS6bsOqsOaPr4qFRJO9ODrUD-2Rih8G95ThCTlCCXP2orAJDQvZktVPS-Okh4JIbS6sb48yrQTqpDxZ5KmI05WNXmpR3b24MElQEF7RvkiOqWST5jwVrVC0kQDvO-xM-RRRpxJ2pM8GJLH5x7YWhfwa_HXVrkncvtBpvxRVSqG-UkUF4_lxh3mqjZpozeDaLMXqhnOPkv87KwcMCYP4r4YNQ4OgRBLJnDouUmXdwbwvg0auE5iuqv7tyIFOQFH9tR4UVsVIODTv4yNeRLFxlU3Bb87-g4Hf4bjtKbrYgOZ5h4OJ0vVn-rDGDxkb3iNiukQ-yKnUbnMtl-QaAbO1tZHxKt-Jt8sbQk-bB7c5WRk7c59U_RB33YAwE_vt8BVrkUEEqA7c8ym58yMlFQOfXsbOz3aQbe4&isca=1

media_folder: 'public/images/blog'
public_folder: '/images/blog'

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/blog'
    create: true
    slug: '{{pageName}}'
    fields:
      - { label: 'Page-Name-with-dashes-only', name: 'pageName', widget: 'string' }
      - { label: 'Blog Title', name: 'blogTitle', widget: 'string' }
      - { label: 'Title Tag', name: 'titleTag', widget: 'string' }
      - { label: 'Description', name: 'blogDescription', widget: 'string' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Tags', name: 'tags', widget: 'list', default: ['post'] }
      - { label: 'Featured Image', name: 'image', widget: 'image' }
      - { label: 'Image Caption', name: 'imageAlt', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
